# Adjusted workflow without testing steps

name: Run Python Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
      if: always()

    - name: Install dev dependencies
      run: |
        pip install black mypy typer

    - name: Lint with Black
      run: |
        python -m black . --check

    - name: Type check with mypy
      run: |
        python -m mypy --config-file mypy.ini . --strict
